### ISSUE TITLE
AGS: Hyprland workspace switch bug

### ISSUE THREAD

**Issue by Ruhrozz** [Serpentian/AlfheimOS#5]
Мне проще на русском написать:

Когда переключаешься между воркспейсами, AGS багуется и не показывает текущий воркспейс правильно. А именно: если на текущем воркспейсе есть окна, то при перемещении воркспейс не меняется, но если пусто то всё ок.

Я пробовал чё-то крутить в AGS даже с помощью чат гпт, но безуспешно, плюс в type script и ags ни в зуб ногой.

Может я пока твой репос копировал напрудил чего, но вроде бы эта ошибка должна присутствовать. Классный репос кстати, очень рад что наткнулся на такой прекрасный конфиг NixOS

**Comment by Serpentian** [comment]
> Когда переключаешься между воркспейсами, AGS багуется и не показывает текущий воркспейс правильно. А именно: если на текущем воркспейсе есть окна, то при перемещении воркспейс не меняется, но если пусто то всё ок.

А как ты между воркспейсами переключаешься? Тип колесиком мыши по overview в баре? Или прям кликаешь, открывается окошко со всеми воркспейсами и переходишь:


![image](https://github.com/user-attachments/assets/0f0d5023-3fca-434b-9a9b-6dd6b962a7e9)


Чет никак не получается воспроизвести. У меня вообще три монитора и все вроде норм работает. 

P.S. Если что, изначально конфиг был утащен отсюда: https://github.com/Aylur/dotfiles, и модифицирован немного. Может, там этого бага не будет, стоит протестить

**Comment by Ruhrozz** [comment]
Переключаюсь win + 1, win + 2 ...

**Comment by Serpentian** [comment]
> Переключаюсь win + 1, win + 2 ..., монитор один.

Тут дело в скрипте, который я использую для переключения между воркспейсами. Скрипт этот [тут](https://github.com/Serpentian/AlfheimOS/blob/9789cce4a67d59ad013b0208285c1297d856115c/user/wm/hyprland/scripts.nix#L6-L30). Это не связано с AGS. Попробуй следующее сделать:

```diff
diff --git a/user/wm/hyprland/binds.nix b/user/wm/hyprland/binds.nix
index f945c66..293e9a6 100644
--- a/user/wm/hyprland/binds.nix
+++ b/user/wm/hyprland/binds.nix
@@ -77,16 +77,16 @@
       "$mod, TAB, focusmonitor, +1"
 
       # Switch workspaces.
-      "$mod, 1,exec,hyprworkspace 1"
-      "$mod, 2,exec,hyprworkspace 2"
-      "$mod, 3,exec,hyprworkspace 3"
-      "$mod, 4,exec,hyprworkspace 4"
-      "$mod, 5,exec,hyprworkspace 5"
-      "$mod, 6,exec,hyprworkspace 6"
-      "$mod, 7,exec,hyprworkspace 7"
-      "$mod, 8,exec,hyprworkspace 8"
-      "$mod, 9,exec,hyprworkspace 9"
-      "$mod, 0,exec,hyprworkspace 10"
+      "$mod, 1,exec,workspace 1"
+      "$mod, 2,exec,workspace 2"
+      "$mod, 3,exec,workspace 3"
+      "$mod, 4,exec,workspace 4"
+      "$mod, 5,exec,workspace 5"
+      "$mod, 6,exec,workspace 6"
+      "$mod, 7,exec,workspace 7"
+      "$mod, 8,exec,workspace 8"
+      "$mod, 9,exec,workspace 9"
+      "$mod, 0,exec,workspace 10"
 
       "$mod CTRL, h, workspace, r-1"
       "$mod CTRL, l, workspace, r+1"
```

Должно помочь)

**Comment by Ruhrozz** [comment]
Я эту темку уже проверял, проверил ещё раз, но ничего не поменялось. Видимо дело не в этом

Не так страшно, что у меня не работет, главное чтобы у тебя такой ошибки не было. Если у тебя нет, то можно будет начать приближать мой репос к твоему, пока мой не превратиться в твой обрано, и таким образом ошибка точно найдётся =)
